pip install xlsxwriter
pip install Spire.Xls

In [1]:
import numpy as np
import pandas as pd

import xlsxwriter
from spire.xls import *
from spire.xls.common import *

In [2]:
pwd

'C:\\git_project\\CU320\\UserReport'

In [3]:
df = pd.read_csv('C:\\git_project\\CU320\\UserReport\\useraccount.csv', encoding='tis-620')

#df2= df.rename(columns={'กลุ่มผ': 'กลุ่ม', 'ผู้': 'Username'})

In [4]:
df.tail()

,Client,Username,ระบบงาน,หน่วยงาน,Initial PW,มีผลจา,มีผลถ,ประเภทผู้,กลุ่ม,ก.เข้าสู่ระบบล้ม,การล็อคผู,เลขที่บ,ผู้สร,สร้างเม,วันที่เข้าระบบ,เวลาเข้าระบบล่า,Initial PW.1,เปลี่ยนแปลงรหัส,เวอร์ชันร,Initial PW.2
535,900,6900FIN01,การเงิน,6900,0,00.00.0000,31.12.9999,A,FIN,0,0,NaN,BASISADMIN,13.09.2019,31.10.2024,14:48:24,0,00.00.0000,NaN,0
536,900,6900HR01,งานบุคคล,6900,0,00.00.0000,31.12.9999,A,HR,0,0,NaN,BASISADMIN,13.09.2019,30.10.2024,16:03:32,0,00.00.0000,NaN,0
537,900,6900MAT01,พัสดุ,6900,0,00.00.0000,31.12.9999,A,MM,0,0,NaN,BASISADMIN,13.09.2019,25.10.2024,10:01:41,0,00.00.0000,NaN,0
538,900,6900MFIN01,การเงิน,6900,0,00.00.0000,31.12.9999,A,FIN,0,0,NaN,BASISADMIN,13.09.2019,03.11.2022,14:41:39,0,00.00.0000,NaN,0
539,900,8900HR01,งานบุคคล,8900,0,00.00.0000,31.12.9999,A,HR,0,0,NaN,BASISADMIN,13.09.2019,28.10.2024,14:35:33,0,00.00.0000,NaN,0

In [5]:
df.head()

,Client,Username,ระบบงาน,หน่วยงาน,Initial PW,มีผลจา,มีผลถ,ประเภทผู้,กลุ่ม,ก.เข้าสู่ระบบล้ม,การล็อคผู,เลขที่บ,ผู้สร,สร้างเม,วันที่เข้าระบบ,เวลาเข้าระบบล่า,Initial PW.1,เปลี่ยนแปลงรหัส,เวอร์ชันร,Initial PW.2
0,900,0100ACC01,บัญชี,100,0,00.00.0000,31.12.9999,A,ACC,0,0,NaN,BASISADMIN,13.09.2019,31.10.2024,13:23:16,0,00.00.0000,NaN,0
1,900,0100ACC02,บัญชี,100,0,00.00.0000,31.12.9999,A,ACC,0,0,NaN,BASISADMIN,13.09.2019,31.10.2024,13:30:40,0,00.00.0000,NaN,0
2,900,0100ACC03,บัญชี,100,0,00.00.0000,31.12.9999,A,ACC,0,0,NaN,BASISADMIN,13.09.2019,31.10.2024,13:39:12,0,00.00.0000,NaN,0
3,900,0100ACC04,บัญชี,100,0,00.00.0000,31.12.9999,A,ACC,0,0,NaN,BASISADMIN,13.09.2019,31.10.2024,14:29:53,0,00.00.0000,NaN,0
4,900,0100ACC05,บัญชี,100,0,00.00.0000,31.12.9999,A,ACC,0,0,NaN,BASISADMIN,13.09.2019,31.10.2024,14:19:18,0,00.00.0000,NaN,0

In [6]:
col = ['ระบบงาน','กลุ่ม','Username']

In [7]:
df2 = df[col]

In [8]:
df2['หน่วยงาน'] = df2['Username'].str[:4]

C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\4197714557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['หน่วยงาน'] = df2['Username'].str[:4]

In [9]:
df2.head()

  ระบบงาน กลุ่ม   Username หน่วยงาน
0   บัญชี   ACC  0100ACC01     0100
1   บัญชี   ACC  0100ACC02     0100
2   บัญชี   ACC  0100ACC03     0100
3   บัญชี   ACC  0100ACC04     0100
4   บัญชี   ACC  0100ACC05     0100

In [10]:
work_unit = df2['หน่วยงาน'].unique()

In [11]:
#df2[df2['หน่วยงาน'] == '2100'].sort_values(by=['ระบบงาน'])

focus_col = ['ระบบงาน','Username']

for i in work_unit:
    df4 = df2[focus_col][df2['หน่วยงาน'] == i].sort_values(by=['ระบบงาน','Username'])
    df4[["ชื่อ_ผู้รับผิดชอบ","นามสกุล_ผู้รับผิดชอบ","รหัสพนักงาน_ผู้รับผิดชอบ", \
        "ชื่อ_ผู้ใช้งาน1","นามสกุล_ผู้ใช้งาน1","รหัสพนักงาน_ผู้ใช้งาน1", \
        "ชื่อ_ผู้ใช้งาน2","นามสกุล_ผู้ใช้งาน2","รหัสพนักงาน_ผู้ใช้งาน2", \
        "ชื่อ_ผู้ใช้งาน3","นามสกุล_ผู้ใช้งาน3","รหัสพนักงาน_ผู้ใช้งาน3",
        "ชื่อ_ผู้ใช้งาน4","นามสกุล_ผู้ใช้งาน4","รหัสพนักงาน_ผู้ใช้งาน4"]] = ""
    
    filename = 'dep_' + i + '.xlsx'
    #print(filename)
    df4.to_excel(filename,index=False)

In [12]:
focus_col = ['ระบบงาน','Username']

col1 = ['บุคลากรผู้ดูแล Username','ผู้ใช้งาน1','ผู้ใช้งาน2','ผู้ใช้งาน3','ผู้ใช้งาน4','ผู้ใช้งาน5','ผู้ใช้งาน6','ผู้ใช้งาน7']
multi_index = pd.MultiIndex.from_product([col1, ["ชื่อ","นามสกุล","รหัสพนักงาน"]])
df10 = pd.DataFrame(columns=multi_index)

for i in work_unit:
    df4 = df2[focus_col][df2['หน่วยงาน'] == i].sort_values(by=['ระบบงาน','Username'])
    data4 = {'ระบบงาน' : df4['ระบบงาน'].values, 'Username' : df4['Username'].values}
    
    df5 = pd.DataFrame(data4)
    # Create the new column level
    new_level = ['System_info']
    # Construct the new MultiIndex
    new_columns = pd.MultiIndex.from_product([new_level, df5.columns])
    # Assign the new MultiIndex
    df5.columns = new_columns
    df5.index += 1
    
    df510 = pd.concat([df5, df10], ignore_index=True)
    df510.index += 1
    
    
       
    filename = 'Dep_' + i + '.xlsx'
    
    writer = pd.ExcelWriter(filename, engine='xlsxwriter')
    df510.to_excel(writer, sheet_name='Sheet1', index_label="No.")
    workbook = writer.book
    worksheet = writer.sheets['Sheet1']
    
    # set column width for 'Sheet1'. If need do the same for other Sheet 
    column_width = 15
    idx = 1
    worksheet.set_column(idx, 30, column_width)

    border_fmt = workbook.add_format({'bottom':2, 'top':2, 'left':2, 'right':2})
    worksheet.conditional_format(xlsxwriter.utility.xl_range(0, 0, 150, len(df510.columns)), {'type': 'no_errors', 'format': border_fmt})
    writer.save()

    #print(filename)
    #df510.to_excel(filename, index = True, index_label="No.")

C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()

C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
C:\Users\hatha\AppData\Local\Temp\ipykernel_26112\3655051142.py:39: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()

In [13]:
df510

  System_info           บุคลากรผู้ดูแล Username                      \
      ระบบงาน  Username                    ชื่อ นามสกุล รหัสพนักงาน
1    งานบุคคล  8900HR01                     NaN     NaN         NaN

  ผู้ใช้งาน1                     ผู้ใช้งาน2          ...  ผู้ใช้งาน4  \
        ชื่อ นามสกุล รหัสพนักงาน       ชื่อ นามสกุล  ... รหัสพนักงาน
1        NaN     NaN         NaN        NaN     NaN  ...         NaN

  ผู้ใช้งาน5                     ผู้ใช้งาน6                     ผู้ใช้งาน7  \
        ชื่อ นามสกุล รหัสพนักงาน       ชื่อ นามสกุล รหัสพนักงาน       ชื่อ
1        NaN     NaN         NaN        NaN     NaN         NaN        NaN


  นามสกุล รหัสพนักงาน
1     NaN         NaN

[1 rows x 26 columns]

In [14]:
col1 = ['ผู้ใช้งาน1','ผู้ใช้งาน2','ผู้ใช้งาน3','ผู้ใช้งาน4','ผู้ใช้งาน5']
data1 = " "
multi_index = pd.MultiIndex.from_product([col1, ["ชื่อ","นามสกุล","รหัสพนักงาน"]])
df10 = pd.DataFrame(data1, columns=multi_index, index=[1])

In [15]:
df10

  ผู้ใช้งาน1                     ผู้ใช้งาน2                     ผู้ใช้งาน3  \
        ชื่อ นามสกุล รหัสพนักงาน       ชื่อ นามสกุล รหัสพนักงาน       ชื่อ
1

                      ผู้ใช้งาน4                     ผู้ใช้งาน5          \
  นามสกุล รหัสพนักงาน       ชื่อ นามสกุล รหัสพนักงาน       ชื่อ นามสกุล
1


  รหัสพนักงาน
1

In [17]:
col1 = ['ผู้รับผิดชอบ','ผู้ใช้งาน1','ผู้ใช้งาน2','ผู้ใช้งาน3','ผู้ใช้งาน4','ผู้ใช้งาน5']

multi_index = pd.MultiIndex.from_product([col1, ["ชื่อ","นามสกุล","รหัสพนักงาน"]])
df10 = pd.DataFrame(columns=multi_index)
df10

Empty DataFrame
Columns: [(ผู้รับผิดชอบ, ชื่อ), (ผู้รับผิดชอบ, นามสกุล), (ผู้รับผิดชอบ, รหัสพนักงาน), (ผู้ใช้งาน1, ชื่อ), (ผู้ใช้งาน1, นามสกุล), (ผู้ใช้งาน1, รหัสพนักงาน), (ผู้ใช้งาน2, ชื่อ), (ผู้ใช้งาน2, นามสกุล), (ผู้ใช้งาน2, รหัสพนักงาน), (ผู้ใช้งาน3, ชื่อ), (ผู้ใช้งาน3, นามสกุล), (ผู้ใช้งาน3, รหัสพนักงาน), (ผู้ใช้งาน4, ชื่อ), (ผู้ใช้งาน4, นามสกุล), (ผู้ใช้งาน4, รหัสพนักงาน), (ผู้ใช้งาน5, ชื่อ), (ผู้ใช้งาน5, นามสกุล), (ผู้ใช้งาน5, รหัสพนักงาน)]
Index: []